from collections.abc import Sequence
from typing import Protocol


class EmbeddingProviderError(Exception): ...


class EmbeddingProviderTransientError(EmbeddingProviderError): ...


class EmbeddingProviderPermanentError(EmbeddingProviderError): ...


class EmbeddingProvider(Protocol):
    @property
    def embedder(self) -> str: ...
    @property
    def model_id(self) -> str: ...
    @property
    def dim(self) -> int: ...

    def embed(self, text: str) -> Sequence[float]: ...
