from collections.abc import Sequence
from typing import Protocol


class EmbeddingProvider(Protocol):
    @property
    def embedder(self) -> str: ...
    @property
    def model_id(self) -> str: ...
    @property
    def dim(self) -> int: ...

    def embed(self, text: str) -> Sequence[float]: ...

    def embed_many(self, texts: list[str]) -> list[list[float]]: ...
